#ifndef IVORY_GAME_STATIC_SETTINGS_HPP
#define IVORY_GAME_STATIC_SETTINGS_HPP

#define IV_ITEM_ICONS_PATH "bin/Assets/Icons/"

#define IV_INVENTORY_ROWS 4
#define IV_INVENTORY_COLS 6
#define IV_INVENTORY_NAME "Inventory"
#define IV_EQUIPPED_ROWS 1
#define IV_EQUIPPED_COLS 8
#define IV_EQUIPPED_NAME "Equipped"


#endif // IVORY_GAME_STATIC_SETTINGS_HPP
